# Generated by Django 2.0.2 on 2018-02-21 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReaGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('chat_id', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('faculty_id', models.CharField(max_length=10)),
                ('course_id', models.CharField(max_length=10)),
                ('asp_keys', models.TextField()),
                ('group_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.ReaGroup')),
            ],
        ),
    ]
