# Generated by Django 2.0.2 on 2018-02-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='group_title',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='ReaGroup',
        ),
    ]
