# Generated by Django 2.0.2 on 2018-02-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_auto_20180221_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='asp_keys',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='course_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='faculty_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
